<a href="https://colab.research.google.com/github/kozakHolota/WoolfDataScience/blob/master/Home_work_1_PavloMryhlotskyi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [1]:
import numpy as np
# Код оголошення векторів не можна змінювати
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} + \begin{pmatrix}
\frac{1}{2}\\
1\\
2\\
3\\
4\\
\end{pmatrix} = \begin{pmatrix}
\frac{1}{2} + 1\\
1 + 2\\
3 + 2\\
4 + 3\\
5 + 4 \\
\end{pmatrix} = \begin{pmatrix}
1\frac{1}{2}\\
3\\
5\\
7\\
9\\
\end{pmatrix}
$$

In [2]:
res = a + b
res

array([[1.5, 3. , 5. , 7. , 9. ]])

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} - \begin{pmatrix}
\frac{1}{2}\\
1\\
2\\
3\\
4\\
\end{pmatrix} = \begin{pmatrix}
1 - \frac{1}{2}\\
2 - 1\\
3 - 2\\
4 - 3\\
5 - 4 \\
\end{pmatrix} = \begin{pmatrix}
\frac{1}{2}\\
1\\
1\\
1\\
1\\
\end{pmatrix}
$$

In [3]:
res = a - b
res

array([[0.5, 1. , 1. , 1. , 1. ]])

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} + \begin{pmatrix}
\frac{1}{2}\\
1\\
2\\
3\\
4\\
\end{pmatrix} ^T = \begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} + \begin{pmatrix}
\frac{1}{2} & 1 & 2 & 3 & 4\\
\end{pmatrix} = \begin{pmatrix}
1 + \frac{1}{2} & 2 + \frac{1}{2} & 3 + \frac{1}{2} & 4 + \frac{1}{2} & 5 + \frac{1}{2}\\
1 + 1 & 2 + 1 & 3 + 1 & 4 + 1 & 5 + 1\\
1 + 2 & 2 + 2 & 3 + 2 & 4 + 2 & 5 + 2\\
1 + 3 & 2 + 3 & 3 + 3 & 4 + 3 & 5 + 3\\
1 + 4 & 2 + 4 & 3 + 4 & 4 + 4 & 5 + 4\\
\end{pmatrix} = \begin{pmatrix}
1\frac{1}{2} & 2\frac{1}{2} & 3\frac{1}{2} & 4\frac{1}{2} & 5\frac{1}{2}\\
2 & 3 & 4 & 5 & 6\\
3 & 4 & 5 & 6 & 7\\
4 & 5 & 6 & 7 & 8\\
5 & 6 & 7 & 8 & 9\\
\end{pmatrix}
$$

In [4]:
# Пояснення:
res = a + b.T
res

array([[1.5, 2.5, 3.5, 4.5, 5.5],
       [2. , 3. , 4. , 5. , 6. ],
       [3. , 4. , 5. , 6. , 7. ],
       [4. , 5. , 6. , 7. , 8. ],
       [5. , 6. , 7. , 8. , 9. ]])

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} * \begin{pmatrix}
\frac{1}{2}\\
1\\
2\\
3\\
4\\
\end{pmatrix} ^T = \begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} * \begin{pmatrix}
\frac{1}{2} & 1 & 2 & 3 & 4\\
\end{pmatrix} = \begin{pmatrix}
1 * \frac{1}{2} + 2 * 1 + 3 * 2 + 4 * 3 + 5 * 4\\
\end{pmatrix} = \begin{pmatrix}
40\frac{1}{2}\\
\end{pmatrix}$$

In [5]:
res = a.dot(b.T)
res

array([[40.5]])

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} * \begin{pmatrix}
\frac{1}{2}\\
1\\
2\\
3\\
4\\
\end{pmatrix}$$

Операція неможлива (кількість стовпців в **a** не дорівнює кількості рядків **b**)

In [6]:
# Пояснення:
res = a.dot(b)
res

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} * \begin{pmatrix}
\frac{1}{2}\\
1\\
2\\
3\\
4\\
\end{pmatrix} = \begin{pmatrix}
1 * \frac{1}{2}\\
2 * 1\\
3 * 2\\
4 * 3\\
5* 4\\
\end{pmatrix} = \begin{pmatrix}
\frac{1}{2}\\
2\\
6\\
12\\
20\\
\end{pmatrix}$$

In [9]:
# Пояснення:
res = a * b
res

array([[ 0.5,  2. ,  6. , 12. , 20. ]])

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} / \begin{pmatrix}
\frac{1}{2}\\
1\\
2\\
3\\
4\\
\end{pmatrix} = \begin{pmatrix}
1 / \frac{1}{2}\\
2 / 1\\
3 / 2\\
4 / 3\\
5 / 4\\
\end{pmatrix} = \begin{pmatrix}
2\\
2\\
1\frac{1}{2}\\
1\frac{1}{3}\\
1\frac{1}{4}\\
\end{pmatrix}$$

In [10]:
# Пояснення:
res = a / b
res

array([[2.        , 2.        , 1.5       , 1.33333333, 1.25      ]])

$$\begin{pmatrix}
1\\
2\\
3\\
4\\
5\\
\end{pmatrix} / \begin{pmatrix}
\frac{1}{2} & 1 & 2 & 3 & 4\\
\end{pmatrix} = \begin{pmatrix}
1 / \frac{1}{2} & 2 / \frac{1}{2} & 3 / \frac{1}{2} & 4 / \frac{1}{2} & 5 / \frac{1}{2}\\
1 / 1 & 2 / 1 & 3 / 1 & 4 / 1 & 5 / 1\\
1 / 2 & 2 / 2 & 3 / 2 & 4 / 2 & 5 / 2\\
1 / 3 & 2 / 3 & 3 / 3 & 4 / 3 & 5 / 3\\
1 / 4 & 2 / 4 & 3 / 4 & 4 / 4 & 5 / 4\\
\end{pmatrix} = \begin{pmatrix}
2 & 4 & 6 & 8 & 8 & 10\\
1 & 2 & 3 & 4 & 5\\
\frac{1}{2} & 1 & 1\frac{1}{2} & 2 & 2\frac{1}{2}\\
\frac{1}{3} & \frac{2}{3} & 1 & 1\frac{1}{3} & 2\frac{1}{3}\\
\frac{1}{4} & \frac{1}{2} & \frac{3}{4} & 1 & 1\frac{1}{4}\\
\end{pmatrix}$$

In [11]:
# Пояснення:
res = a / b.T
res

array([[ 2.        ,  4.        ,  6.        ,  8.        , 10.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 0.5       ,  1.        ,  1.5       ,  2.        ,  2.5       ],
       [ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ,  1.25      ]])

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

## 2.1 Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$
$$
M_1 =
\begin{pmatrix}
0.5 & 0 \\
0 & 3
\end{pmatrix},
\quad
x =
\begin{pmatrix}
2 \\
1
\end{pmatrix}
$$

$$
M_1 x =
\begin{pmatrix}
0.5 & 0 \\
0 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
2 \\
1
\end{pmatrix}
=
\begin{pmatrix}
0.5 \cdot 2 + 0 \cdot 1 \\
0 \cdot 2 + 3 \cdot 1
\end{pmatrix}
=
\begin{pmatrix}
1 \\
3
\end{pmatrix}
$$

## 2.2 Відобрази вектор $x$ відносно початку координат.
$$
M_2 = \left(\begin{array}{cc}
-1 & 0\\
0 & -1
\end{array}\right)
$$
$$
M_2x = \left(\begin{array}{cc}
-1 & 0\\
0 & -1
\end{array}\right) * \left(\begin{array}{cc}
1\\
3
\end{array}\right) = \left(\begin{array}{cc}
-1\\
-3
\end{array}\right)
$$

## 2.3 Перенеси вектор $x$, задавши відповідну матрицю і помноживши на неї,  на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 =
\begin{pmatrix}
-3 \\
1
\end{pmatrix}
$$
$$
M_3 x =
\begin{pmatrix}
1 & 0 & -3 \\
0 & 1 & 1 \\
0 & 0 & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
-3 \\
1 \\
1
\end{pmatrix}
=
\begin{pmatrix}
1 \cdot (-3) + 0 \cdot 1 + (-3) \cdot 1 \\
0 \cdot (-3) + 1 \cdot 1 + 1 \cdot 1 \\
0 \cdot (-3) + 0 \cdot 1 + 1 \cdot 1
\end{pmatrix}
=
\begin{pmatrix}
-6 \\
2 \\
1
\end{pmatrix}
$$
$$
M_3 x =
\begin{pmatrix}
-6 \\
2
\end{pmatrix}
$$

#### 2.4 Змісти(shear) вектор $x$ на 60° по вісі $OY$.


$$
M_{4x} =
\begin{pmatrix}
1 & 0 \\
\sqrt{3} & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
-6 \\
2
\end{pmatrix}
=
\begin{pmatrix}
1 \cdot (-6) + 0 \cdot 2 \\
\sqrt{3} \cdot (-6) + 1 \cdot 2
\end{pmatrix}
=
\begin{pmatrix}
-6 \\
-6 \sqrt{3} + 2
\end{pmatrix}
$$

#### 2.5 Поверни вектор $x$ на 30°.

$$
\theta = \frac{30 \pi}{180} = \frac{\pi}{6}
$$
$$
R(\theta) =
\begin{pmatrix}
\cos\left( \frac{\pi}{6} \right) & -\sin\left( \frac{\pi}{6} \right) \\
\sin\left( \frac{\pi}{6} \right) & \cos\left( \frac{\pi}{6} \right)
\end{pmatrix}
=
\begin{pmatrix}
\frac{\sqrt{3}}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{\sqrt{3}}{2}
\end{pmatrix}
$$
$$
M_{5x} = R(\theta) \cdot
\begin{pmatrix}
-6 \\
-6 \sqrt{3} + 2
\end{pmatrix}
=
\begin{pmatrix}
\frac{\sqrt{3}}{2} \cdot (-6) + \left(-\frac{1}{2}\right) \cdot \left(-6 \sqrt{3} + 2\right) \\
\frac{1}{2} \cdot (-6) + \frac{\sqrt{3}}{2} \cdot \left(-6 \sqrt{3} + 2\right)
\end{pmatrix}
$$

Обчислимо:

$$
\begin{aligned}
\text{Перша координата:} \quad & -3 \sqrt{3} + \frac{6 \sqrt{3} - 2}{2} = -3 \sqrt{3} + 3 \sqrt{3} - 1 = -1 \\
\text{Друга координата:} \quad & -3 + \frac{-18 + 2 \sqrt{3}}{2} = -3 - 9 + \sqrt{3} = -12 + \sqrt{3}
\end{aligned}
$$
$$
\boxed{M_{5x} =
\begin{pmatrix}
-1 \\
-12 + \sqrt{3}
\end{pmatrix}
}
$$

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

## Перемноження матриць

Нехай маємо наступне множення:

$$
M = M_6 \cdot M_5 \cdot M_4 \cdot M_2 \cdot M_1
$$

де

$$
M_1 = \begin{pmatrix}
-\frac{1}{2} & \frac{\sqrt{3}}{2} \\
-\frac{\sqrt{3}}{2} & -\frac{1}{2}
\end{pmatrix}, \quad
M_2 = \begin{pmatrix}
1 & 0 \\
\sqrt{3} & 1
\end{pmatrix}, \quad
M_4 = \begin{pmatrix}
0 & 0.5 \\
0 & 0
\end{pmatrix}
$$

$$
M_5 = \begin{pmatrix}
0 & 0 \\
0 & -3
\end{pmatrix}, \quad
M_6 = \begin{pmatrix}
\frac{1}{2} & 0 \\
0 & -3
\end{pmatrix}
$$

### Крок 1. Обчислюємо $M_2 \cdot M_1$

$$
M_2 \cdot M_1 =
\begin{pmatrix}
1 & 0 \\
\sqrt{3} & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
-\frac{1}{2} & \frac{\sqrt{3}}{2} \\
-\frac{\sqrt{3}}{2} & -\frac{1}{2}
\end{pmatrix}
=
\begin{pmatrix}
-\frac{1}{2} & \frac{\sqrt{3}}{2} \\
-\frac{\sqrt{3}}{2} & -\frac{1}{2}
\end{pmatrix}
$$

### Крок 2. Обчислюємо $M_5 \cdot M_4$

$$
M_5 \cdot M_4 =
\begin{pmatrix}
0 & 0 \\
0 & -3
\end{pmatrix}
\cdot
\begin{pmatrix}
0 & 0.5 \\
0 & 0
\end{pmatrix}
=
\begin{pmatrix}
0 & 0 \\
0 & 0
\end{pmatrix}
$$

### Крок 3. Остаточне множення:

$$
M = M_6 \cdot \left(M_5 \cdot M_4\right) \cdot \left(M_2 \cdot M_1\right)
=
\begin{pmatrix}
\frac{1}{2} & 0 \\
0 & -3
\end{pmatrix}
\cdot
\begin{pmatrix}
-\frac{\sqrt{3}}{2} & \frac{1}{2} \\
-3 & 0
\end{pmatrix}
=
\begin{pmatrix}
-\frac{\sqrt{3}}{4} & \frac{1}{4} \\
-6 & 0
\end{pmatrix}
$$

### Відповідь:

$$
M =
\begin{pmatrix}
-\frac{\sqrt{3}}{4} & \frac{1}{4} \\
-6 & 0
\end{pmatrix}
$$

### Застосуємо результуючу матрицю до початкового вектора

$$
M =
\begin{pmatrix}
-\dfrac{\sqrt{3}}{4} & \dfrac{1}{4} \\
-6 & 0
\end{pmatrix},
\quad
\vec{x} =
\begin{pmatrix}
2 \\
1
\end{pmatrix}
$$

Знайдемо добуток $begin:math:text$ M \\cdot \\vec{x} $end:math:text$:

$$
M \cdot \vec{x} =
\begin{pmatrix}
-\dfrac{\sqrt{3}}{4} & \dfrac{1}{4} \\
-6 & 0
\end{pmatrix}
\cdot
\begin{pmatrix}
2 \\
1
\end{pmatrix}
=
\begin{pmatrix}
-\dfrac{2\sqrt{3}}{4} + \dfrac{1}{4} \\
-12
\end{pmatrix}
=
\begin{pmatrix}
\dfrac{-2\sqrt{3} + 1}{4} \\
-12
\end{pmatrix}
$$

# Завдання 2 (Альтернативне)

In [ ]:
import cv2 as cv
import urllib
import numpy as np
from google.colab.patches import cv2_imshow as cv_imshow

# Read an image
def read_image_by_url(url):
    req = urllib.request.urlopen(url)
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
    img = cv.imdecode(arr, -1)
    return img

url = ''

img = read_image_by_url(url)

In [ ]:
cv_imshow(img)